# Generated by Django 4.2.2 on 2023-06-24 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
